export const projectBeeDefinitions = [
  {
    name: "BootstrapRuntimeBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/bootstrap-runtime/bee.1.0.0.js",
    factoryExport: "bootstrapRuntimeBee",
  },
  {
    name: "DispatchApiRequestBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/dispatch-api-request/bee.1.0.0.js",
    factoryExport: "dispatchApiRequestBee",
  },
  {
    name: "OptionsApiRequestBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/options-api-request/bee.1.0.0.js",
    factoryExport: "optionsApiRequestBee",
  },
  {
    name: "HealthApiRequestBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/health-api-request/bee.1.0.0.js",
    factoryExport: "healthApiRequestBee",
  },
  {
    name: "ListProjectsApiRequestBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/list-projects-api-request/bee.1.0.0.js",
    factoryExport: "listProjectsApiRequestBee",
  },
  {
    name: "CreateProjectHttpRequestBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/create-project-http-request/bee.1.0.0.js",
    factoryExport: "createProjectHttpRequestBee",
  },
  {
    name: "EnsureSessionHttpRequestBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/ensure-session-http-request/bee.1.0.0.js",
    factoryExport: "ensureSessionHttpRequestBee",
  },
  {
    name: "SubmitPromptAsyncHttpRequestBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/submit-prompt-async-http-request/bee.1.0.0.js",
    factoryExport: "submitPromptAsyncHttpRequestBee",
  },
  {
    name: "ListMessagesApiRequestBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/list-messages-api-request/bee.1.0.0.js",
    factoryExport: "listMessagesApiRequestBee",
  },
  {
    name: "ListProjectSessionsApiRequestBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/list-project-sessions-api-request/bee.1.0.0.js",
    factoryExport: "listProjectSessionsApiRequestBee",
  },
  {
    name: "ListLlmProvidersApiRequestBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/list-llm-providers-api-request/bee.1.0.0.js",
    factoryExport: "listLlmProvidersApiRequestBee",
  },
  {
    name: "SetActiveLlmProviderApiRequestBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/set-active-llm-provider-api-request/bee.1.0.0.js",
    factoryExport: "setActiveLlmProviderApiRequestBee",
  },
  {
    name: "NotFoundApiRequestBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/not-found-api-request/bee.1.0.0.js",
    factoryExport: "notFoundApiRequestBee",
  },
  {
    name: "CreateProjectApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/create-project-api/bee.1.0.0.js",
    factoryExport: "createProjectApiBee",
  },
  {
    name: "EnsureSessionApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/ensure-session-api/bee.1.0.0.js",
    factoryExport: "ensureSessionApiBee",
  },
  {
    name: "QueueUserMessageApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/queue-user-message-api/bee.1.0.0.js",
    factoryExport: "queueUserMessageApiBee",
  },
  {
    name: "CallLlmApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/call-llm-api/bee.1.0.0.js",
    factoryExport: "callLlmApiBee",
  },
  {
    name: "QueueAssistantMessageApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/queue-assistant-message-api/bee.1.0.0.js",
    factoryExport: "queueAssistantMessageApiBee",
  },
  {
    name: "QueueAssistantErrorApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/queue-assistant-error-api/bee.1.0.0.js",
    factoryExport: "queueAssistantErrorApiBee",
  },
  {
    name: "PassThroughErrorApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/pass-through-error-api/bee.1.0.0.js",
    factoryExport: "passThroughErrorApiBee",
  },
  {
    name: "QueuePromptAsyncApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/queue-prompt-async-api/bee.1.0.0.js",
    factoryExport: "queuePromptAsyncApiBee",
  },
  {
    name: "RunLocalToolCallsApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/run-local-tool-calls-api/bee.1.0.0.js",
    factoryExport: "runLocalToolCallsApiBee",
  },
  {
    name: "ToolLocalListFilesApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/tool-local-list-files-api/bee.1.0.0.js",
    factoryExport: "toolLocalListFilesApiBee",
  },
  {
    name: "ToolLocalReadFileApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/tool-local-read-file-api/bee.1.0.0.js",
    factoryExport: "toolLocalReadFileApiBee",
  },
  {
    name: "ToolLocalSearchTextApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/tool-local-search-text-api/bee.1.0.0.js",
    factoryExport: "toolLocalSearchTextApiBee",
  },
  {
    name: "ToolLocalWriteFileApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/tool-local-write-file-api/bee.1.0.0.js",
    factoryExport: "toolLocalWriteFileApiBee",
  },
  {
    name: "ToolSkillReadApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/tool-skill-read-api/bee.1.0.0.js",
    factoryExport: "toolSkillReadApiBee",
  },
  {
    name: "ToolSkillGoalDecompositionApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/tool-skill-goal-decomposition-api/bee.1.0.0.js",
    factoryExport: "toolSkillGoalDecompositionApiBee",
  },
  {
    name: "ToolBrowserNavigateApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/tool-browser-navigate-api/bee.1.0.0.js",
    factoryExport: "toolBrowserNavigateApiBee",
  },
  {
    name: "ToolBrowserClickApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/tool-browser-click-api/bee.1.0.0.js",
    factoryExport: "toolBrowserClickApiBee",
  },
  {
    name: "ToolBrowserScreenshotApiBee",
    version: "1.0.0",
    modulePath: "./swarm/bees/tool-browser-screenshot-api/bee.1.0.0.js",
    factoryExport: "toolBrowserScreenshotApiBee",
  },
]

export const projectDanceFiles = [
  "./swarm/dances/bootstrap-runtime/dance.1.0.0.json",
  "./swarm/dances/dispatch-api-request/dance.1.0.0.json",
  "./swarm/dances/options-api-request/dance.1.0.0.json",
  "./swarm/dances/health-api-request/dance.1.0.0.json",
  "./swarm/dances/list-projects-api-request/dance.1.0.0.json",
  "./swarm/dances/create-project-http-request/dance.1.0.0.json",
  "./swarm/dances/ensure-session-http-request/dance.1.0.0.json",
  "./swarm/dances/submit-prompt-async-http-request/dance.1.0.0.json",
  "./swarm/dances/list-messages-api-request/dance.1.0.0.json",
  "./swarm/dances/list-project-sessions-api-request/dance.1.0.0.json",
  "./swarm/dances/list-llm-providers-api-request/dance.1.0.0.json",
  "./swarm/dances/set-active-llm-provider-api-request/dance.1.0.0.json",
  "./swarm/dances/not-found-api-request/dance.1.0.0.json",
  "./swarm/dances/create-project-api/dance.1.0.0.json",
  "./swarm/dances/ensure-session-api/dance.1.0.0.json",
  "./swarm/dances/submit-prompt-async-api/dance.1.0.0.json",
  "./swarm/dances/submit-prompt-api/dance.1.0.0.json",
  "./swarm/dances/run-local-tool-calls-api/dance.1.0.0.json",
  "./swarm/dances/tool-local-list-files-api/dance.1.0.0.json",
  "./swarm/dances/tool-local-read-file-api/dance.1.0.0.json",
  "./swarm/dances/tool-local-search-text-api/dance.1.0.0.json",
  "./swarm/dances/tool-local-write-file-api/dance.1.0.0.json",
  "./swarm/dances/tool-skill-read-api/dance.1.0.0.json",
  "./swarm/dances/tool-skill-goal-decomposition-api/dance.1.0.0.json",
  "./swarm/dances/tool-browser-navigate-api/dance.1.0.0.json",
  "./swarm/dances/tool-browser-click-api/dance.1.0.0.json",
  "./swarm/dances/tool-browser-screenshot-api/dance.1.0.0.json",
]

export const projectConfig = {
  i18n: {
    language: process.env.SWARM_LANG || "zh-CN",
  },
  bootstrap: {
    dance: "BootstrapRuntimeDance",
    inputHoney: {
      type: "RuntimeBootstrapHoney",
      payload: {},
    },
  },
  server: {
    host: "127.0.0.1",
    port: 3000,
    frontendRoot: "../frontend",
    indexFile: "index.html",
  },
  runtime: {
    projectsRoot: process.env.SWARM_PROJECTS_ROOT || "../projects",
  },
  llm: {
    activeProviderId: process.env.SWARM_LLM_ACTIVE_PROVIDER || "1",
    providers: [],
  },
  localTools: {
    enabled: (process.env.SWARM_LOCAL_TOOLS_ENABLED || "true").toLowerCase() === "true",
    workspaceRoot: process.env.SWARM_WORKSPACE_ROOT || "../..",
    skillsRoot: process.env.SWARM_SKILLS_ROOT || "../Skills",
    obscuraCommand: process.env.SWARM_OBSCURA_COMMAND || "obscura",
    dances: {
      runToolCalls: "RunLocalToolCallsApiDance",
      listFiles: "ToolLocalListFilesApiDance",
      readFile: "ToolLocalReadFileApiDance",
      searchText: "ToolLocalSearchTextApiDance",
      writeFile: "ToolLocalWriteFileApiDance",
      readSkill: "ToolSkillReadApiDance",
      runGoalDecompositionSkill: "ToolSkillGoalDecompositionApiDance",
      browserNavigate: "ToolBrowserNavigateApiDance",
      browserClick: "ToolBrowserClickApiDance",
      browserScreenshot: "ToolBrowserScreenshotApiDance",
    },
  },
  api: {
    dances: {
      dispatchRequest: "DispatchApiRequestDance",
      optionsRequest: "OptionsApiRequestDance",
      healthRequest: "HealthApiRequestDance",
      listProjectsRequest: "ListProjectsApiRequestDance",
      createProjectRequest: "CreateProjectHttpRequestDance",
      ensureSessionRequest: "EnsureSessionHttpRequestDance",
      submitPromptAsyncRequest: "SubmitPromptAsyncHttpRequestDance",
      listMessagesRequest: "ListMessagesApiRequestDance",
      listProjectSessionsRequest: "ListProjectSessionsApiRequestDance",
      listLlmProvidersRequest: "ListLlmProvidersApiRequestDance",
      setActiveLlmProviderRequest: "SetActiveLlmProviderApiRequestDance",
      notFoundRequest: "NotFoundApiRequestDance",
      createProject: "CreateProjectApiDance",
      ensureSession: "EnsureSessionApiDance",
      submitPromptAsync: "SubmitPromptAsyncApiDance",
      submitPrompt: "SubmitPromptApiDance",
    },
    honeyTypes: {
      dispatchRequest: "DispatchApiRequestHoney",
      createProject: "CreateProjectRequestHoney",
      ensureSession: "EnsureSessionRequestHoney",
      submitPromptAsync: "SubmitPromptAsyncRequestHoney",
      submitPrompt: "SubmitPromptRequestHoney",
    },
  },
  initialState: {
    projects: [],
    sessions: {},
    sessionByProject: {},
  },
}
